hydra:
  output_subdir: Null
  run:
    dir: .
  searchpath:
    - pkg://config


eval_folder:
  - /home/robotic/Downloads/phidch_ws/src/bmw-lab/scripts/sordi-2022/data/eval



defaults:
  - _self_

  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

