hydra:
  output_subdir: Null
  run:
    dir: .
  searchpath:
    - pkg://config


data_folder: 
  - data/SORDI_2022_Industrial_Rooms/SORDI_2022_h4022_industrial rooms 360p
  - data/SORDI_2022_Industrial_Rooms/SORDI_2022_h4023_industrial rooms
  - data/SORDI_2022_Regensburg_plant/SORDI_2022_h4024_regensburg plant 360p
  - data/SORDI_2022_Regensburg_plant/SORDI_2022_h4025_regensburg plant

eval_folder:
  - /home/robotic/Downloads/sordi-2022/eval



defaults:
  - _self_

  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

